### ISSUE TITLE
Crossbuild is slow

### ISSUE THREAD

**Issue by slrtbtfs** [prometheus/promu#176] opened 2020-02-11 17:46 UTC
Currently promu spins up a new docker container for each crossbuild target, with the respective native toolchain installed. https://github.com/prometheus/promu/blob/2e745da3feab32c483524de1b78efbffe13e9334/cmd/crossbuild.go#L198-L203

Since Go 1.5 this isn't necessary any more: https://dave.cheney.net/2015/08/22/cross-compilation-with-go-1-5

Using this "new" feature speeds up the crossbuild process significantly. For the PromQL language server the speed up is more than 10x.

Since crossbuilding is the slowest part of the Prometheus CI, it would make sense to update promu to use the crossbuild capabilities of newer go releases.

**Comment by simonpasquier** [comment] 2020-02-14 11:34
> Currently promu spins up a new docker container for each crossbuild target, with the respective native toolchain installed. 

The later part isn't 100% accurate as it's only true for builds with `CGO_ENABLED=1`:

https://github.com/prometheus/promu/blob/2e745da3feab32c483524de1b78efbffe13e9334/cmd/crossbuild.go#L152-L163

When `CGO_ENABLED=0` all builds happen in the same container. The problem is more that each GOOS/GOARCH build variant needs to recompile everything from scratch as there is nothing cached.

I think there are 2 things that can be improved:
* almost all the `.promu.yml` configurations (if not all)  adds `-a` to the build command which forces rebuilding of all packages. I suspect it is a safety measure for cgo builds but we probably don't need it if cgo isn't enabled.
* we could save and reuse the build cache across CI runs.

**Comment by SuperQ** [comment] 2021-03-17 15:56
Fixed with https://github.com/prometheus/promu/pull/208

**Closed by SuperQ** 2021-03-17 15:56 UTC
Labels: enhancement, help wanted
