### ISSUE TITLE
cannot find package "github.com/google/go-github/v25/github" in any of:

### ISSUE THREAD

**Issue by chevvi** [prometheus/promu#218] opened 2021-03-23 09:53 UTC
Ok, Why does i have this error if  i simply do it:
```
go get -u github.com/prometheus/promu
cannot find package "github.com/google/go-github/v25/github" in any of:
	/usr/lib/golang/src/github.com/google/go-github/v25/github (from $GOROOT)
	/home/worker/go/src/github.com/google/go-github/v25/github (from $GOPATH)
# cd /home/worker/go/src/github.com/prometheus/common; git pull --ff-only
Your configuration specifies to merge with the ref 'refs/heads/master'
from the remote, but no such ref was fetched.
package github.com/prometheus/common/version: exit status 1
```

_Originally posted by @chevvi in https://github.com/prometheus/promu/issues/216#issuecomment-803967302_

**Comment by carlpett** [comment] 2021-03-24 15:40
This also affects the CI builds for windows_exporter. I _think_ it happens when installing in non-module aware mode (ie `GO111MODULE=off go get github.com/prometheus/promu`, which was at least previously the way to install tools without getting them into go.mod), since the google/go-github module appears to not be non-module compatible by not keeping older versions in the repo?

**Comment by SuperQ** [comment] 2021-03-24 15:53
Go 1.16 has changed the behavior of how modules interact when building tools with `go get`.

The "new way" is to use `go install github.com/prometheus/promu@VERSION`. You can also substitute `latest` for the version.

**Comment by carlpett** [comment] 2021-03-24 15:59
Yeah, I'm aware, and we should update. We haven't updated knowingly, but I'll have to check if something changed under our feet here.

**Comment by repl-mike-roest** [comment] 2021-04-15 19:35
This also seems to be effecting build for https://github.com/justwatchcom/elasticsearch_exporter

**Comment by leominov** [comment] 2021-04-19 16:23
Build also fails via prometheus/golang-builder that pulled by promu downloaded from release page, not sure if I can change in this case:

```
promu crossbuild
/!\ unknown/unhandled platforms: [darwin/386]
1.16-base: Pulling from prometheus/golang-builder
004f1eed87df: Pull complete 
caa6e70f78e1: Pull complete 
1eb575d854c0: Pull complete 
aa6405fcdbb9: Pull complete 
bacfdbe289aa: Pull complete 
356777896934: Pull complete 
Digest: sha256:64d87e482dcdb46794c557c84520bc0a76614235d01cb385dd12b4d878a095cf
Status: Downloaded newer image for quay.io/prometheus/golang-builder:1.16-base
quay.io/prometheus/golang-builder:1.16-base
> running the base builder docker image
71e8c2a31f0a45b4a588ca9a192fd319f7eb3563720048a583cfa7778a2af005
# darwin-amd64
github.com/prometheus/promu (download)
github.com/google/go-github (download)
cannot find package "github.com/google/go-github/v25/github" in any of:
	/usr/local/go/src/github.com/google/go-github/v25/github (from $GOROOT)
	/go/src/github.com/google/go-github/v25/github (from $GOPATH)
```

**Comment by MarbolanGos** [comment] 2021-08-09 13:40
This also impacts this exporter: https://github.com/GSI-HPC/lustre_exporter

**Comment by bljusruk** [comment] 2022-10-04 08:18
This problem also affects build of [https://github.com/adhocteam/script_exporter](https://github.com/adhocteam/script_exporter)

**Comment by SuperQ** [comment] 2022-10-04 08:38
Those problems need to be fixed by updating their use of promu. This is not a bug in promu.

**Closed by SuperQ** 2022-10-04 08:38 UTC
